spring:
  application:
    name: news
  datasource:
    url: jdbc:mysql://localhost:3307/news
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090